#!/usr/bin/env python
# coding: utf8
import random


def erzeugePropTabllenAufgaben(mitPfeilen=True,mitBeschr=True):
    paare=[['Anzahl','Preis in \euro{}'],['Zeit in min','Preis in \euro{}'],['Anzahl','Volumen in l'],['Tage','Strecke in km'],['Kinder','Gruppen'],['Anzahl','Kartons'],['Zeit in min','Anzahl']]
    title=random.choice(paare)
    op=random.choice(['*','/'])
    d1,d2,multi=[random.randint(1,12),random.randint(1,12),random.randint(1,12)]
    if d1==d2:
        d2=d2*random.randint(2,4)
    if op=='*':
        l=[d1,d1*multi]
        r=[d2,d2*multi]
    else:
        l=[d1*multi,d1]
        r=[d2*multi,d2]
    afg=tikzPropTabelle(l,r,title=title,mitPfeilen=mitPfeilen,mitBeschr=mitBeschr,mitLsg=False)
    lsg=tikzPropTabelle(l,r,title=title,mitLsg=True)
    return [afg,lsg,[[]]]

def erzeugePropDiagrammAufgaben(diagrammVorgegeben=True,mitText=True):
    paare=[['Anzahl', 'Preis in \euro{}'], ['Zeit in min', 'Preis in \euro{}'], ['Anzahl', 'Volumen in l'],
           ['Tage', 'Strecke in km'], ['Kinder', 'Gruppen'], ['Anzahl', 'Kartons'], ['Zeit in min', 'Anzahl']]
    auswahl=random.choice(paare)
    multi=random.randint(2,10)
    afg=afg+[F'{"Übertrage die Werte" if diagrammVorgegeben else "Erstelle aus den Werten"} der Tabelle {"in das " if diagrammVorgegeben else "ein"} Diagramm.\\\\' if mitText else '\\phantom{e}']
    xwerte=[1]
    for i in range(4):
        xwerte.append(xwerte[-1]+random.randint(1,3))
    ywerte=[x*multi for x in xwerte]
    tabelle=tikzTabelle(tabelle=[auswahl]+[[strNW(x),strNW(x*multi)]for x in xwerte],dim=[1.5,0.5],spaltenBreite=[],zeilenHoehe=[],newCBuchst='A',tabellenPos=[-4.5,4.5])
    if diagrammVorgegeben:
        diagramm=diagrammTikzVorgBreiteHoehe(zuPlotten=[],xAchse=[0,xwerte[-1],xwerte[-1]+1],yAchse=[0,ywerte[-1],11],xlabel=auswahl[0],ylabel=auswahl[1],urspr=[0,0],mitUmrandung=False)
    else:
        diagramm=[F'\\node at (7,11) {{ }};']
    afg=afg+ ([] if nurText else (tabelle[:-1]+diagramm+[tabelle[-1]]))
    afg=afg+ ([] if nurText else ['}'])

    diagramm=diagrammTikzVorgBreiteHoehe(zuPlotten=[[F'{v}*x','black']],xAchse=[0,6,7],yAchse=[0,vMax,11],xlabel='t in s',ylabel='s in  m',urspr=[0,0],mitUmrandung=False)
    lsg=tabelle[:-1]+diagramm+[tabelle[-1]]
    return [afg,lsg,[v]]

def propDreisatz():
    paare=[['Anzahl', 'Preis in \euro{}'], ['Zeit in min', 'Preis in \euro{}'], ['Anzahl', 'Volumen in l'],
           ['Tage', 'Strecke in km'], ['Kinder', 'Gruppen'], ['Anzahl', 'Kartons'], ['Zeit in min', 'Anzahl']]
    auswahl=random.choice(paare)
    xStart=random.randint(2,10)
    xZiel=random.randint(2,10)
    while xStart==xZiel:
        xZiel=random.randint(2, 12)
    yStart=random.randint(2,5)
    afg=dreiSatz(links=[strNW(x, True) for x in [xStart, '', xZiel]],rechts=[strNW(yStart*xStart),'',''],title=auswahl, breit=True,ohneKlammernLinks=True,ohneKlammernRechts=True)
    lsg=dreiSatz(links=[strNW(x, True) for x in [xStart, '1', xZiel]],
                 rechts=[strNW(x, True) for x in [yStart*xStart, yStart, yStart*xZiel]],title=auswahl, breit=True)
    return [afg,lsg,[]]