#!/usr/bin/env python
# coding: utf8
import random


def erzeugePropTabllenAufgaben(mitPfeilen=True,mitBeschr=True):
    paare=[['Anzahl','Preis in \euro{}'],['Zeit in min','Preis in \euro{}'],['Anzahl','Volumen in l'],['Tage','Strecke in km'],['Kinder','Gruppen'],['Anzahl','Kartons'],['Zeit in min','Anzahl']]
    title=random.choice(paare)
    op=random.choice(['*','/'])
    d1,d2,multi=[random.randint(1,12),random.randint(1,12),random.randint(1,12)]
    if d1==d2:
        d2=d2*random.randint(2,4)
    if op=='*':
        l=[d1,d1*multi]
        r=[d2,d2*multi]
    else:
        l=[d1*multi,d1]
        r=[d2*multi,d2]
    afg=tikzPropTabelle(l,r,title=title,mitPfeilen=mitPfeilen,mitBeschr=mitBeschr,mitLsg=False)
    lsg=tikzPropTabelle(l,r,title=title,mitLsg=True)
    return [afg,lsg,[[]]]
